/**
 * Explicit API (FR-API-001..005): `env.NAME` / `env.get(name)` are synchronous and return exactly
 * `process.env[name]`. Holds no secrets of its own (FR-API-004) — only what cb put in the environment.
 */

/** Augmented per project by `.cb/env.d.ts` (generated by `cb types`) with the environment's variable names. */
// biome-ignore lint/suspicious/noEmptyInterface: filled in by declaration merging from .cb/env.d.ts
export interface CbEnv {}

/**
 * Typed access: `env.NAME` for names generated by `cb types` (typos fail at compile time); `env.get(name)` for
 * anything else and never throws.
 */
export type CbEnvAccess = { readonly [K in keyof CbEnv]: CbEnv[K] } & {
  get(name: keyof CbEnv | (string & {})): string | undefined;
};

const SNAPSHOT_VAR = "CB_SNAPSHOT_PATH";

function missing(name: string): Error {
  return new Error(
    `cb: ${name} is not set for this environment. Ask an admin to add it in the dashboard (project → environment → Variables), then restart with "cb run".`,
  );
}

export const env: CbEnvAccess = new Proxy({} as CbEnvAccess, {
  get(_target, prop) {
    if (prop === "get") return (name: string) => process.env[name];
    if (typeof prop !== "string") return undefined;
    const value = process.env[prop];
    // FR-API-002 under cb run: a variable the app expects but cb did not provide is a configuration error.
    // FR-API-005 outside cb run (e.g. production): plain process.env semantics.
    if (value === undefined && process.env[SNAPSHOT_VAR] && prop !== "then" && prop !== "toJSON") throw missing(prop);
    return value;
  },
  has: (_target, prop) => typeof prop === "string" && process.env[prop] !== undefined,
  ownKeys: () => Object.keys(process.env),
  getOwnPropertyDescriptor: (_target, prop) =>
    typeof prop === "string" && process.env[prop] !== undefined
      ? { enumerable: true, configurable: true, value: process.env[prop] }
      : undefined,
  set() {
    throw new Error("cb: env is read-only. Change values in the dashboard.");
  },
});

export default env;
