import fs from "node:fs";
import path from "node:path";
import type { Command } from "commander";
import { fetchBootstrap } from "../../agent/agent";
import { PACKAGE_NAME, PROJECT_DIR } from "../../constants";
import { newCorrelationId } from "../../shared/correlation";
import { requireServerCredentials } from "../../shared/credentials";
import { requireProjectConfig } from "../../shared/project-config";
import { out, resolveServer } from "../context";
import { resolveEnvironmentName } from "./run";

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** The .d.ts body: one readonly string per variable, merged into `CbEnv` and `NodeJS.ProcessEnv`. */
export function renderEnvTypes(keys: string[], label: string): string {
  const props = [...new Set(keys)]
    .sort()
    .map((k) => `    readonly ${IDENT.test(k) ? k : JSON.stringify(k)}: string;`)
    .join("\n");
  return `// Generated by \`cb types\` for ${label}. Do not edit; re-run \`cb types\` after variables change.
// Names only — values are delivered at run time by \`cb run\`.
export {};

declare module "${PACKAGE_NAME}" {
  interface CbEnv {
${props}
  }
}

declare global {
  namespace NodeJS {
    interface ProcessEnv {
${props.replaceAll("    readonly ", "      readonly ")}
    }
  }
}
`;
}

/** FR-PKG-010: generate `.cb/env.d.ts` with this environment's variable names. */
export function registerTypesCommand(program: Command): void {
  program
    .command("types")
    .description("Generate .cb/env.d.ts with your environment's variable names")
    .option("--env <name>", "environment")
    .option("--json", "print the variable names as JSON instead of writing the file")
    .action(async (opts: { env?: string; json?: boolean }) => {
      const { config, root } = requireProjectConfig();
      const server = resolveServer(config.server);
      const creds = await requireServerCredentials(server);
      const environment = await resolveEnvironmentName(
        config.projectId,
        opts.env,
        config.defaultEnvironment,
        process.env,
      );
      const b = await fetchBootstrap({
        serverUrl: server,
        token: creds.token,
        projectId: config.projectId,
        orgId: config.orgId,
        environment,
        correlationId: newCorrelationId(),
      });
      const keys = [...Object.keys(b.plain), ...b.listeners.flatMap((l) => Object.keys(l.env))];
      if (opts.json) {
        out(JSON.stringify({ environment, keys: [...new Set(keys)].sort() }));
        return;
      }
      const file = path.join(root, PROJECT_DIR, "env.d.ts");
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, renderEnvTypes(keys, `${config.projectSlug ?? config.projectId} / ${environment}`));
      out(`cb: wrote ${path.relative(process.cwd(), file) || file} (${new Set(keys).size} variable(s)).`);
    });
}
